[package]
name = "spacepackets"
version = "0.1.0"
edition = "2021"
authors = ["Robin Mueller <muellerr@irs.uni-stuttgart.de>"]
description = "Generic implementations for various CCSDS and ECSS packet standards"
homepage = "https://egit.irs.uni-stuttgart.de/rust/spacepackets"
repository = "https://egit.irs.uni-stuttgart.de/rust/spacepackets"
license = "Apache-2.0"
keywords = ["no-std", "space", "packets", "ccsds", "ecss"]
categories = ["aerospace", "aerospace::space-protocols", "no-std", "hardware-support", "embedded"]
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
zerocopy = "0.6.1"
crc = "3.0.0"
delegate = "0.7.0"

[dependencies.serde]
version = "1.0.142"
default-features = false
features = ["derive"]

[dependencies.chrono]
version = "0.4.20"
default-features = false
features = ["serde"]

[dependencies.num-traits]
version = "0.2"
default-features = false

[dev-dependencies.postcard]
version = "1.0.1"

[features]
default = ["std"]
std = ["chrono/std", "chrono/clock", "alloc"]
alloc = ["postcard/alloc"]
